#!/bin/sh
python latent_active_learning/scripts/train_franka_kitchen.py with franka_kitchen student_type=intent_entropy
python latent_active_learning/scripts/train_franka_kitchen.py with franka_kitchen student_type=unsupervised
python latent_active_learning/scripts/train_franka_kitchen.py with franka_kitchen student_type=iterative_random
python latent_active_learning/scripts/train_franka_kitchen.py with franka_kitchen student_type=supervised
