#!/bin/sh
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=supervised
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=unsupervised
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=iterative_random
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=intent_entropy
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=action_entropy
python latent_active_learning/scripts/train_hbc.py with discrete_3targets_boxworld student_type=action_intent_entropy 
